# Generated by Django 4.2.1 on 2023-06-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
